### PR TITLE
Change how to create the generated class package name

### LINKED ISSUE #262: PermissionsDispatcher makes wrong class hierarchy
When I set @RuntimePermission and related annotations in the nested class, PermissionDispatcher generates classes with wrong class hierarchy.    
If there's a code like this,
```
package test;
public class Test {
  //Not an Activity
  @RuntimePermission
  public static class NestedActivity extends AppCompatActivity {
    //An Activity
    @NeedsPermission("android.permission.ACCESS_FINE_LOCATION")//Some permissions for this method
    public void permissionRequiredMethod(){
       //Some code here
    }
  }
}
```
From this code, PermissionDispatcher generates a code like this:
```
package test.Test;
public class NestedActivityPermissionDispatcher{
  //Generated code here
}
```
This generated code makes some error where referencing Test class and package-private methods in generated code. (This error doesn't happen at my code.)    
    
I think generated code must be like this to work correctly:
```
package test;
public class Test$NestedActivityPermissionDispatcher{
  //Generated code here
}
```

### PR DESCRIPTION
**Pull request by shiraji**
Close #262

### CODE REVIEW

File: processor/src/main/kotlin/permissions/dispatcher/processor/util/Extensions.kt [hunk 1]
```diff
@@ -7,15 +7,20 @@ import permissions.dispatcher.OnShowRationale
...
  * Returns the package name of a TypeElement.
  */
 fun TypeElement.packageName(): String {
-    val qn = this.qualifiedName.toString()
-    return qn.substring(0, qn.lastIndexOf('.'))
+    val enclosingElement = enclosingElement
+    return when (enclosingElement) {
+        is TypeElement -> enclosingElement.packageName()
+        is PackageElement -> enclosingElement.qualifiedName.toString()
+        else -> ""
```
Comment (shiraji) [inline processor/src/main/kotlin/permissions/dispatcher/processor/util/Extensions.kt]: I did this, sInce [this line](https://github.com/hotchemi/PermissionsDispatcher/blob/master/processor/src/main/kotlin/permissions/dispatcher/processor/RuntimePermissionsElement.kt#L16) comes before `init` block, TypeElement hasn't validated, yet. If `enclosingElement` returns non-`TypeElement`/`PackageElement`, I believe some validation fails, later.

Comment (aurae) [inline processor/src/main/kotlin/permissions/dispatcher/processor/util/Extensions.kt]: In these cases, would it be feasible to walk up the "enclosingElement" hierarchy to check for `TypeElement`/ `PackageElement` higher up the chain?

Comment (shiraji) [inline processor/src/main/kotlin/permissions/dispatcher/processor/util/Extensions.kt]: Make sense. I was expecting `null` here. Let me fix this.

**Comment by hotchemi** [comment]
@shiraji Thx! Before review can we wait a conclusion of my question? https://github.com/hotchemi/PermissionsDispatcher/issues/262#issuecomment-271240627
As I wrote, I'm not for allowing user to do a wrong approach so let me clarify the pros of the change.

**Comment by shiraji** [comment]
i will add and rebase the commit as soon as possible.

**Comment by shiraji** [comment]
done.

**Comment by hotchemi** [comment]
Thx!!!

**Comment by aurae** [comment]
Great job!
